### ISSUE TITLE
`release-please` GHA fails due to expired access token

### ISSUE THREAD

**Issue by timfish** [nodejs/import-in-the-middle#150]
https://github.com/nodejs/import-in-the-middle/actions/runs/10149322265/job/28064006186#step:2:380

@legendecas, I think this was your token that expired!

**Comment by legendecas** [comment]
I can confirm the permission scope is correct on the audit page: https://github.com/organizations/nodejs/settings/personal-access-tokens/337284.

Maybe the token value is not correctly configured.

**Comment by legendecas** [comment]
Ahh, I granted repo write access to @nodejs-github-bot on nodejs/import-in-the-middle and it works now.

**Comment by legendecas** [comment]
https://github.com/nodejs/import-in-the-middle/pull/151

**Comment by timfish** [comment]
Many thanks!
