### ISSUE TITLE
Add contributor

### ISSUE THREAD

**Issue by jsumners-nr** [nodejs/import-in-the-middle#158]
Please add @bizob2828 as a contributor. He's the lead engineer on my team at New Relic, and it would be helpful if he could fill-in when I am not available. Case and point: 
+ https://github.com/nodejs/import-in-the-middle/pull/155#issuecomment-2379524329
+ https://github.com/nodejs/import-in-the-middle/pull/155#issuecomment-2382884492

**Comment by jsumners-nr** [comment]
🤷‍♂️

**Comment by timfish** [comment]
@bengl is listed as the maintainer of the [`import-in-the-middle-maintainers`](https://github.com/orgs/nodejs/teams/import-in-the-middle-maintainers) team, so I guess he could add to it.

**Comment by timfish** [comment]
@bizob2828 can click the "Request to join" button in the top right of the team linked above and I guess that will go so someone 🤷‍♂️

**Comment by bizob2828** [comment]
> @bizob2828 can click the "Request to join" button in the top right of the team linked above and I guess that will go so someone 🤷‍♂️

Sure. I'll give that a shot

**Comment by bizob2828** [comment]
I don't have permissions to view that

**Comment by legendecas** [comment]
It seems the Node.js org is been locked down for billing issue. I am going to raise a ticket.

**Comment by legendecas** [comment]
Invitation sent. Feel free to close the issue once @bizob2828 accepts the invite.

**Comment by jsumners-nr** [comment]
Thank you everyone.
