### ISSUE TITLE
Add dygabo as a maintainer

### ISSUE THREAD

**Issue by legendecas** [nodejs/import-in-the-middle#159]
@dygabo requested to join the @nodejs/import-in-the-middle-maintainers team (via the GitHub UI).

Since the team grants write permission to the repo so I'd like to post a public issue before acknowledging the request.

It'd be great to have existing team members to endorse their request.

**Comment by pichlermarc** [comment]
@dygabo is a Dynatrace employee, he works on Dynatrace's Node.js Agent and has very in-depth knowledge about the topic. He's also part of the [Node.js loaders team.](https://github.com/orgs/nodejs/teams/loaders) His knowledge about Node.js internals far surpasses mine. 

I endorse their request. :slightly_smiling_face:

**Comment by dygabo** [comment]
Hello, thanks for the tag. I made that request a few months ago when the repo was created but did not have time to engage more until now. The subject is interesting to me and to us as a team.

**Comment by legendecas** [comment]
Request acknoledged!
