### ISSUE TITLE
Are sequential patched supported?

### ISSUE THREAD

**Issue by TheAsda** [nodejs/import-in-the-middle#98]
As far as i understand and according to some testing being done if there are multiple multiple hooks attached to the same package the last one will be eventually used in application. Am i right? If so are there any methods to apply sequential patches to the package. The case is that i'm using library that's patched the package i want to patch.

Library version: 1.8.0
Node version: 20.11.1

**Comment by TheAsda** [comment]
So i did some tesing with import and require.
Branch with import-in-the-middle: https://github.com/TheAsda/import-in-the-middle-issue/tree/master
Branch with require-in-the-middle: https://github.com/TheAsda/import-in-the-middle-issue/tree/require
There are two scripts that apply some patching to fastify package. With require everything works as expected:
![image](https://github.com/DataDog/import-in-the-middle/assets/35863331/a1b5819b-f6a3-4e60-977f-ea147870bb71)
But the same example with import applies only the latest patch:
![image](https://github.com/DataDog/import-in-the-middle/assets/35863331/d03d1c43-710e-4810-a057-9b9c41abb4f4)
I also tried different methods such as using `register` from the module package, applying patches in single file. The result is the same

**Comment by TheAsda** [comment]
Looks like the issue is with proxy created in https://github.com/DataDog/import-in-the-middle/blob/main/lib/register.js. `hook` is called with the scoped namespace that is the same every time the hook is called

**Comment by TheAsda** [comment]
I added `getter` similar to `setter` to be able to get the latest namespace after modification
![image](https://github.com/DataDog/import-in-the-middle/assets/35863331/cc191b68-34ca-48e7-a3ed-333f1c4cd058)

**Comment by timfish** [comment]
> I added `getter` similar to `setter` to be able to get the latest namespace after modification

Could you submit a PR to fix this or do you have a patch I could try?

**Comment by TheAsda** [comment]
I managed to fix the issue with default import patching but when i tested patching named exports tests failed :( Right now i don't have a solution to this problem
